[package]
name = "linux-rtic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rtic"

[dependencies]
linux-rtic-macros = { path = "macros" }
rtic-core = "0.3.1"
heapless = "0.7"
lazy_static = "1.4"
pcp_mutex = { path = "../pcp_mutex" }
